export const CLOTH_EVADE_CHANCE = 0;
export const CLOTH_DEFENCE_MULTIPLIER = 0;
export const CLOTH_MOVE_DISTANCE_MULTIPLIER = 0;

export const LIGHT_EVADE_CHANCE = -0.05;
export const LIGHT_DEFENCE_MULTIPLIER = 0.5;
export const LIGHT_MOVE_DISTANCE_MULTIPLIER = -0.10;

export const MEDIUM_EVADE_CHANCE = -0.10;
export const MEDIUM_DEFENCE_MULTIPLIER = 1.0;
export const MEDIUM_MOVE_DISTANCE_MULTIPLIER = -0.20;

export const HEAVY_EVADE_CHANCE = -0.25;
export const HEAVY_DEFENCE_MULTIPLIER = 2.0;
export const HEAVY_MOVE_DISTANCE_MULTIPLIER = -0.35;
