name: Build and Deploy
on:
  push:
    branches:
      - master  # Set this to the branch you want to deploy from

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'  # Set this to the node version you prefer

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
      env:
        NODE_ENV: production

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist # The folder the action should deploy.
  
